version: "3"

services:

  dev:
    container_name: go-dev
    build:
      context: .
    # docker run -i
    stdin_open: true
    # docker run -t
    tty: true
    networks:
      - localstack
    volumes:
      - "./aws:/root/.aws"

  localstack:
    container_name: go-localstack
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    hostname: localstack
    networks:
      - localstack
    # https://docs.localstack.cloud/localstack/configuration
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - DOCKER_SOCK=unix:///var/run/docker.sock
      # custom
      - SQS_QUEUE_NAME=go-sqs-example
    volumes:
      - ".localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # run custom scripts: requires credentials
      - "./aws:/root/.aws"
      - './entrypoint:/docker-entrypoint-initaws.d'

networks:
  localstack:
